### ISSUE TITLE
Whitelisting TLDs using "urlclassifier.trstrictackingSkipURLs"

### ISSUE THREAD

**Issue by BillyJoeJimBob** [yokoffing/Betterfox#124]
In ETP, whitelisting a few TLDs e.g.: user_pref("urlclassifier.trackingSkipURLs", "*.com, *.net, *.org"); effectively disables most blocking of general tracking content while retaining other protections under Firefox ETP Strict Mode.  Add-on content blockers such as uBlock Origin provide configurable & granular blocking & whitelisting of tracking content, while whitelisting ETP via the Firefox URLbar shield drops all tracking protection on that site.  Also, having 2 different content blockers (ETP + UBO) complicates trouble-shooting broken sites.

My question is whether whitelisting TLDs using  "urlclassifier.trackingSkipURLs" also disables the filtering of Cross-site cookies, Cryptominers, Fingerprinters & Social media trackers (these categories of filters reside in the same master  blocklist: https://github.com/mozilla-services/shavar-prod-lists).   I've searched for an answer to this, but I have been unable to find any documentation on "SkipURLs" other than what you have posted here & on Reddit.

Thank you for any insights you may have on this.

**Comment by yokoffing** [comment]
## Short Answer
I typed out a longer answer first, but let me give you the short answer, after I've had some time to think on what you may really be asking.

You didn't state it outright, but if you're wanting all the protections that are turned on with `Strict` without the `Block tracking content in all windows` part, then I would suggest setting ETP to `Custom` and unselecting `Tracking Protection`.

![Screenshot 2022-12-01 183656](https://user-images.githubusercontent.com/11689349/205181633-308aa8e0-e7e5-4565-927c-e3a4a5eaa4c8.png)

Then go through the first part of `Securefox` and manually enable all the prefs I have marked on the side that say `enabled with "Strict"`, with is only around three prefs or so. But I would double-check all the prefs, TBH. Betterfox used to use `Custom` but we've been on `Strict` for awhile now. So look at them all under `SECTION: TRACKING PROTECTION`.

## Long Answer

>whitelisting a few TLDs e.g.: user_pref("urlclassifier.trackingSkipURLs", "*.com, *.net, *.org");

For the record: I don't recommend you do this.

>Also, having 2 different content blockers (ETP + UBO) complicates trouble-shooting broken sites.

That's not the norm for 99% of sites, unless there's a known bug for `Strict` breaking a random site. Especially if it doesn't involve embedded social posts, which is what the exemptions are for in the `user.js`. I never have to turn off `Strict` TP, and I visit/test a variety of sites. You should also read reference link 4 in `Securefox` for this pref:

https://github.com/yokoffing/Betterfox/blob/3f533f236f5b008e4e2d3c81b2651ffc26eb8cae/Securefox.js#L22-L31

>My question is whether whitelisting TLDs using "urlclassifier.trackingSkipURLs" also disables the filtering of Cross-site cookies, Cryptominers, Fingerprinters & Social media trackers 

No, that's why they're their own distinct categories. It only affects the "tracking content" pref (e.g., like you saw in the `Custom` options). Also, hence why there's a separate allowlist pref, `urlclassifier.features.socialtracking.skipURLs`, for social media tracking specifically. These individual blocking categories are parts of a bigger whole that make up Enhanced Tracking Protection (ETP) in Firefox.

>I've searched for an answer to this, but I have been unable to find any documentation on "SkipURLs" other than what you have posted here & on Reddit.

I wouldn't have known it existed if it wasn't for that guy on reddit lol. I wish Firefox would adopt this from Brave and add GUI options for social embed posts.

**Comment by BillyJoeJimBob** [comment]
yokoffing: Thank you for your reply.

You answered my main question, that whitelisting entire ubiquitous TLDs in strict mode was not advisable, even with a content-blocking extension.  I will stick with ETP strict mode because it involves a single setting that is clearly indicated in Firefox preferences menu & URLbar shield rather than multiple hidden about:config settings in custom mode.   ETP strict causes breakage of images in https://www.drudgereport.com (caused by blocking pbs.twimg.com) and images or comments in a few other sites that are unbroken by whitelisting twitter, reddit as well as some specific google and amazon ad servers.

**Comment by yokoffing** [comment]
> ETP strict causes breakage of images in https://www.drudgereport.com (caused by blocking pbs.twimg.com) and images or comments in a few other sites that are unbroken by whitelisting twitter, reddit as well as some specific google and amazon ad servers

By default, yes. But I can view these images at `https://www.drudgereport.com`, and if you're using the the `user.js`, you should be able to too:

https://github.com/yokoffing/Betterfox/blob/32705478d23c1a0a8298918e296732f50e64f19a/user.js#L23-L24

We already make allowance for `.twimg.com`, so this should be a non-issue.

Since we allow some of these social requests through, you can limit them by somewhat by add [this](https://github.com/yokoffing/filterlists/blob/main/privacy_essentials.txt) list to uBO.
