### ISSUE TITLE
[Question] Switch from Arkenfox to Betterfox

### ISSUE THREAD

**Issue by HyperCriSiS** [yokoffing/Betterfox#180]
Hi,

I switched from Arkenfox to Betterfox user.js and I wonder if I need to reset the FF settings to make things work as it should?

Thanks,
Hyper

**Comment by Patrxgt** [comment]
Yes, you have to restart your settings and delete Arkenfox before the installation of this user.js

**Comment by yokoffing** [comment]
Without delving into specifics, yes, I would. But instead of manually altering those prefs, just create a new profile altogether and transfer your browser data over.

I've been working on a guide every now and again on how to transfer your current profile settings into a new profile. Here's a rough draft of what I have:

1. Download the [user.js](https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js,), append the file with your overrides, and place it into a new Firefox "profile folder". Find the profile folder location by entering "about:support" into urlbar and locating "Profile Folder" row. Click "Open Folder" button. (See [here](https://support.mozilla.org/kb/profiles-where-firefox-stores-user-data/)).

2. Migrate your personal stuff from the old profile by copying appropriate files from backup and place them into the new profile (or read [here](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data#w_what-information-is-stored-in-my-profile)):

`cert9.db` - Certificates
`content-prefs.sqlite` - Site-specific preferences
`favicons.sqlite` - Bookmarks icons
`handlers.json` - Download actions
`key4.db` - Passwords
`logins.json` - Passwords
`permissions.sqlite` - Site-specific preferences
`persdict.dat` - Personal dictionary
`pkcs11.txt` - Security device settings
`places.sqlite` - Bookmarks

3. Install your extensions, change your search engine, setup your `userChrome` (if applicable), etc.

Thank you for your question!
