### ISSUE TITLE
Consider adding overscroll to Smoothfox.js

### ISSUE THREAD

**Issue by crying-qwq** [yokoffing/Betterfox#197]
Consider adding an option in Smoothfox.js to enable overscroll (`apz.overscroll.enabled`)

It only works on touchpads (and presumably touchscreens).

How it looks:

https://github.com/yokoffing/Betterfox/assets/122160911/33dc62b1-ec99-4f8f-87af-a96a8b445236

**Comment by yokoffing** [comment]
`apz.overscroll.enabled` is already `true`(enabled by default) on Firefox Stable and Nightly on my Macbook.

What am I missing here?

**Comment by crying-qwq** [comment]
Oh okay, sorry. It seems like it is not on by default on Linux (at least not on Fedora's build), didn't think to test that on other platforms

**Comment by yokoffing** [comment]
No, I appreciate the feedback. I don't have a Linux machine to test at this time, and there's not a lot of documentation around scrolling prefs.

I can include it if it's not default for Linux. And `apz.overscroll.enabled` was included in previous Smoothfox builds, but I think I removed it because I assumed it was default on all platforms.
