### ISSUE TITLE
Currentness of LibreWolf Overrides

### ISSUE THREAD

**Issue by AlphaElwedritsch** [yokoffing/Betterfox#292]
The last librewolf.overrides.cfg is 9 months old.

Does this have to be adjusted from time to time?
Is this done by the team?
Is this maintained by the team?

Or is it the user themselves?

What about the librewolf.overrides.cfg in general?

Thank you

**Comment by yokoffing** [comment]
I made the overrides file to make Librewolf more like Betterfox. It is not connected to the Librewolf team at all. I have not dedicated time to update it. I may just delete it eventually.

Please go here for more info: https://librewolf.net/docs/settings/. I don't really use Librewolf, so I'm not the best to answer questions.

btw:
https://github.com/yokoffing/Betterfox/blob/dfb297bbfbbc41ee1210cd7da53e3d243fccb3b3/librewolf.overrides.cfg#L19-L23

**Comment by AlphaElwedritsch** [comment]
OK, thanks
So it's maybe better to use FF or FF ESR with the BetterFox user.js to have fuull BetterFox support.
In the sense of: `Betterfox is an opinionated preference list inspired by the [law of diminishing returns](http://psychologyofwellbeing.com/wp-content/uploads/2017/01/Diminishing-Returns.gif) and the [minimum effective dose](https://medium.com/the-mission/less-is-more-the-minimum-effective-dose-e6d56625931e).`

**Comment by aqtoo** [comment]
Sorry to boost a closed issue, so would the recommendation just be use FF along side Betterfox, instead of attempting to use Librewolf with the Overrides?

**Comment by yokoffing** [comment]
@aqtoo Yes.

If you review [the links provided at the top of the Librewolf file](https://github.com/yokoffing/Betterfox/issues/292#issuecomment-2123068327), you'd see that Librewolf has lower performance in benchmark tests compared to regular Firefox. In the Speedometer 2.1 and JetStream 2.1 tests, Librewolf scored 74% and 89% of Firefox 116, respectively.

Hence:
https://github.com/yokoffing/Betterfox/blob/dfb297bbfbbc41ee1210cd7da53e3d243fccb3b3/librewolf.overrides.cfg#L19

For overall performance, you're better off using a user.js file for Firefox rather than using a fork like Librewolf, Floorp, Waterfox, etc.

**Comment by ioc2e3** [comment]
> [@aqtoo](https://github.com/aqtoo)是的。
> 
> 如果您查看[Librewolf 文件頂部提供的鏈接](https://github.com/yokoffing/Betterfox/issues/292#issuecomment-2123068327)，您會發現與常規 Firefox 相比，Librewolf 在基準測試中的性能較低。在 Speedometer 2.1 和 JetStream 2.1 測試中，Librewolf 的得分分別為 Firefox 116 的 74% 和 89%。
> 
> 因此：
> 
> [Betterfox/librewolf.overrides.cfg](https://github.com/yokoffing/Betterfox/blob/dfb297bbfbbc41ee1210cd7da53e3d243fccb3b3/librewolf.overrides.cfg#L19)
> 
> 第 19 行 [dfb297b](/yokoffing/Betterfox/commit/dfb297bbfbbc41ee1210cd7da53e3d243fccb3b3)
> 
> // 最好只使用 user.js 檔案：
> 為了整體效能，最好使用 Firefox 的 user.js 文件，而不是使用 Librewolf、Floorp、Waterfox 等分支。

Thanks for the response ...

.
