### ISSUE TITLE
Very high ram usage 

### ISSUE THREAD

**Issue by User3254548** [yokoffing/Betterfox#296]
i don't ever remember that edge went over 1.2 gb ram usage

but my final betterfox uses 1.6 to 1.9

i saw alot of people complain in the past where other users told them that it will free up when needed

but all of them said that windows gives up bc it doesn't work

and I'm wondering what am i supposed to to with the information that "GPU" uses one gig of ram like???

https://imgur.com/a/sx0kizh

**Comment by yokoffing** [comment]
This is not Betterfox-specific. In general, Firefox uses more RAM than Chromium browsers mostly in part due to [Fission](https://github.com/yokoffing/Betterfox/blob/9756922ee951f9c0dd09f1e7037b93089a661963/Securefox.js#L71-L83) (sandboxing). But I agree, Mozilla needs to find a way to manage RAM usage better.

You can lower RAM usage by "undoing" Fission (see Option 3 [here](https://github.com/yokoffing/Betterfox/blob/9756922ee951f9c0dd09f1e7037b93089a661963/Fastfox.js#L613-L660)), but at the cost of security. Don't take that as my endorsement or recommendation. (It's not.)
