### ISSUE TITLE
Location is not available when i open folder the root directory in about:profiles

### ISSUE THREAD

**Issue by Ashvalano** [yokoffing/Betterfox#300]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [ ] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [ ] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [ ] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
The directory stated in the about:profiles apparently does not exists.

![image](https://github.com/yokoffing/Betterfox/assets/59825653/1c7f38b7-5bb6-4e54-80e2-8139f497669d)

![image](https://github.com/yokoffing/Betterfox/assets/59825653/6e012c29-c6e4-4c67-9bed-63f9cc039168)

![image](https://github.com/yokoffing/Betterfox/assets/59825653/a6a9916a-44bf-4d0c-8a3c-2c632bac69d6)

I've already configured the settings so that hidden folders appear as default.

 - OS: Windows 11
 - Browser: Firefox
 - Version: 127.0

**Comment by philg-dev** [comment]
Hi @Ashvalano 

this doesn't sound like an issue that's caused by anything Betterfox does.
I assume you're asking this because you're trying to apply the `user.js` to that folder?

The profile folder in Roaming should always exist and I honestly have no clue how your Firefox is even running with anything other than the complete default settings, since your Roaming folder doesn't even have a Mozilla folder to begin with. The data stored in `%APPDATA%\Mozilla\Firefox\Profiles\` contains all your customized user settings, bookmarks, extensions, etc. So if this folder is missing entirely, Firefox probably starts completely "clean" every time, like on a fresh install on a new machine.

I don't know how your `%APPDATA%\Mozilla` folder got deleted, but when you re-install Firefox it should get created again. If for some miraculous reason however, your current Firefox configuration is customized to your liking and is running with no other problems, then you might want to dig deeper to find out why it's even working to begin with - because you would probably want to carry your current configuration over and keep it.

Best Regards,

Phil

**Comment by Ashvalano** [comment]
hi @philg-dev yeah i should just probably reinstall it. Thanks!

**Comment by Ashvalano** [comment]
i have reinstalled firefox by downloading the installer in a browser and the folder appears now. the problem probably is that i installed firefox through microsoft store in the first place.
