### ISSUE TITLE
Firefox Weather Widget not being blocked by Betterfox

### ISSUE THREAD

**Issue by FifthWit** [yokoffing/Betterfox#311]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [x] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
*A clear and concise description of what the bug is.*
A new FireFox feature (for me) added a widget with the weather at the top left of the new tab screen on a fresh install
**To Reproduce**
*Steps to reproduce the behavior:*
```
1. Go to 'Download FireFox'
2. Install BetterFox
3. Open New Tab
4. Look at the top left and it should have a weather widget in specific mine is sponsered by AccuWeather
```

**Expected behavior**
*A clear and concise description of what you expected to happen.*
The Widget would be gone along with all the data it takes
**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image for gh issue](https://github.com/user-attachments/assets/93809313-4d8b-499a-9bf1-4b1c595cb678)
**Desktop (please complete the following information):**
 - OS: Windows 10 Home

 - Browser: FireFox
 - Version: 128.0.3 (64-bit)

**Additional context**
*Add any other context about the problem here.*
unsure if everyone has this but at least on the most recent version its appearing for me

**Comment by yokoffing** [comment]
Documented. Just forgot to un-comment it from since I was using Nightly as a daily driver for awhile:
https://github.com/yokoffing/Betterfox/blob/abe7e9d4d8620d66577c6b45cfb4ebdcbbfbf285/Peskyfox.js#L290-L291

You can still turn it off in about:config or adding it to your personal user.js.

There also should be UI for this in the settings, if there isn't already.

**Comment by winter-again** [comment]
Not sure if helpful, but (in ref. to the commit above) I had to specify `browser.newtabpage.activity-stream.system.showWeather` as `false` too to get the weather widget to go away.

**Comment by yokoffing** [comment]
@winter-again I've tested on two systems with vanilla Firefox stable, and I only had to use `browser.newtabpage.activity-stream.showWeather`. I've also confirmed that this is the pref that changes if you disable the Weather widget from the new tab page.

`system.showWeather` removes it altogether as an option from the gear icon on the new tab page.

Since I am disabling it by default, perhaps we should use that instead.
