### ISSUE TITLE
New Tab shortcut option always turns off itself on startup

### ISSUE THREAD

**Issue by frokiez** [yokoffing/Betterfox#347]
New Tab shortcuts always reset to disabled after I open Firefox once or twice after closing it.
Only happens after I install Betterfox.

<img width="1280" alt="Screenshot 2024-11-30 at 21-08-01 New Tab" src="https://github.com/user-attachments/assets/4dc550c8-3227-43e3-bddd-25bd4d10ac6e">

**Comment by philg-dev** [comment]
Did you have a look at this setting yet?

https://github.com/yokoffing/Betterfox/blob/429abb61f52726b7c6f1675bccca32bbb5359c02/Peskyfox.js#L287

```
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false); // Shortcuts
```

**Comment by frokiez** [comment]
> Did you have a look at this setting yet?
> 
> https://github.com/yokoffing/Betterfox/blob/429abb61f52726b7c6f1675bccca32bbb5359c02/Peskyfox.js#L287

Swapped 'false' to 'true' but the problem still exists.

**Comment by philg-dev** [comment]
What do you mean, you swapped `false` to `true` and also deleted the whole line? Did you delete it from your copy of the betterfox user.js? If you did this in `about:config` it will not work, since the betterfox `user.js` is always applied entirely at firefox startup and therefore it will override any configuration changes you made through the normal firefox GUI and/or about:config, if the respective preferences are in the `user.js`.

To customize your betterfox, you're supposed to use the personal overrides section.
See here: https://github.com/yokoffing/Betterfox/wiki/Common-Overrides

I just tested flipping the switch / checkbox that's on your screenshot on a brand new profile, and if you look at `browser.newtabpage.activity-stream.feeds.topsites` in `about:config`, you will see that this value changes with the state of the UI switch. So this should be the correct property that is responsible for your problem.

**Comment by frokiez** [comment]
I didn't know before how to override scripts. I followed the instructions and now it's working.
Thank you.

**Comment by philg-dev** [comment]
I'm glad I could help.

Since your problem seems to be resolved, would you please close the issue?
